apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    lab: lab3
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream backend {
        server go-app-service:8080;
      }
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /api/ {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
        location /health {
          proxy_pass http://backend/health;
        }
      }
    }
